name: Init py test

on:
  pull_request:
    paths-ignore:
      - '**.yml'
      - '**.yaml'
  push:
    branches:
      - main
    paths-ignore:
      - '**.yml'
      - '**.yaml'

jobs:
  build:
    name: EditorConfig Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run EditorChecker
        uses: editorconfig-checker/action-editorconfig-checker@v1.0.0
        with:
          args: -config .editorconfig
  test:
    name: Launch main.py
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run main.py
        run: |
          python main.py

